# Generated by Django 5.0.1 on 2024-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50),
        ),
    ]
