# Generated by Django 5.0.1 on 2024-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_asset_asset_category_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='time_log',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
