# Generated by Django 5.0.1 on 2024-03-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_check_changes_delete_dbmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='start_time',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
