# Generated by Django 5.0.1 on 2024-03-05 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_asset_end_time_remove_asset_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='orientation',
            field=models.FileField(default=0, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
    ]
