# Generated by Django 5.0.1 on 2024-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_exit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit',
            name='asset',
        ),
        migrations.AddField(
            model_name='exit',
            name='asset_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exit',
            name='asset_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
