# Generated by Django 5.0.1 on 2024-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exit',
            name='asset_id',
            field=models.IntegerField(unique=True),
        ),
    ]
