# Generated by Django 5.0.1 on 2024-04-05 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_asset_asset_id_alter_exit_asset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('works', models.CharField(max_length=100)),
                ('safety_insurance', models.FileField(upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpeg', 'jpg'])])),
                ('insurance_expiry', models.DateField()),
            ],
        ),
    ]
