# Generated by Django 5.0.1 on 2024-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('active_time', models.TimeField()),
                ('inactive_time', models.TimeField()),
            ],
        ),
    ]
