# Generated by Django 5.0.1 on 2024-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_timeschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='active_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='inactive_time',
            field=models.CharField(max_length=50),
        ),
    ]
