# Generated by Django 5.0.1 on 2024-04-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_timeschedule_active_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orientation',
        ),
    ]
